version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
  api:
    image: api-events-image
    ports:
      - 9091:8080
    links:
      - "mongodb"